# Generated by Django 5.1.6 on 2025-02-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='SysAdmin', max_length=128),
            preserve_default=False,
        ),
    ]
